name: CI/CD Pipeline API ML

# 1. QUAND DECLENCHER LE PIPELINE ?
on:
  push:
    # Se lance quand tu pousses sur main ou sur tes branches de développement
    branches: [ "main", "feature/**" ]
  pull_request:
    # Répond à l'exigence : "Une validation avant fusion de branches"
    branches: [ "main" ]

jobs:
  # ==========================================
  # ENVIRONNEMENT DE TEST (Intégration Continue)
  # ==========================================
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          poetry run pytest

  # ==========================================
  # ENVIRONNEMENT DE PROD (Déploiement Continu)
  # ==========================================
  deploy:
    runs-on: ubuntu-latest
    needs: test # DÉPENDANCE : Attend que le job 'test' soit terminé et réussi
    if: github.ref == 'refs/heads/main' # SÉCURITÉ : Ne s'exécute QUE sur la branche main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Push to Hugging Face
        # Assure-toi d'avoir créé un secret HF_TOKEN dans les settings de ton repo GitHub
        env:
          HF_TOKEN: ${{ secrets.HUGGINFACETOKEN }}
        run: |
          git remote add space https://apinsun:$HF_TOKEN@huggingface.co/spaces/apinsun/Projet5
          git push --force space main
